name: Sanitize Mongo

on:
  workflow_dispatch:
  schedule:
    # Runs at 3:30am UTC - 9am IST
    - cron: '30 3 * * *'

jobs:
  sanitize:
    name: Sanitize the database
    runs-on: ubuntu-latest
    steps:
      - name: Make the REST request
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://server.psn.hackclub.com/admin/sanitize/'
          method: 'POST'
          username: ${{ secrets.BASIC_USER }}
          password: ${{ secrets.BASIC_PASSWORD }}
